CREATE TABLE IF NOT EXISTS auth_user (id text PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, email_verified boolean NOT NULL DEFAULT false, image text, created_at timestamp NOT NULL, updated_at timestamp NOT NULL);
CREATE TABLE IF NOT EXISTS legal_acceptances (user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, terms_version text NOT NULL, accepted_at timestamptz NOT NULL DEFAULT now(), recording_law_acknowledged_at timestamptz NOT NULL DEFAULT now(), legal_bundle_sha256 text NOT NULL, PRIMARY KEY(user_id, terms_version));
ALTER TABLE legal_acceptances ADD COLUMN IF NOT EXISTS legal_bundle_sha256 text NOT NULL DEFAULT 'ea207ddf60331f6b136fe4fdf3749484827d97315dc8e8a726c5febecdc5af64';
ALTER TABLE legal_acceptances ALTER COLUMN legal_bundle_sha256 DROP DEFAULT;
CREATE INDEX IF NOT EXISTS legal_acceptances_owner ON legal_acceptances(user_id);
CREATE TABLE IF NOT EXISTS auth_rate_limit (id text PRIMARY KEY, key text NOT NULL UNIQUE, count integer NOT NULL, last_request bigint NOT NULL);
CREATE TABLE IF NOT EXISTS billing_customers (user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, livemode boolean NOT NULL, customer_id text, checkout_attempt text NOT NULL, checkout_session_id text, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id, livemode));
CREATE UNIQUE INDEX IF NOT EXISTS billing_customer_stripe_id ON billing_customers(customer_id);
CREATE TABLE IF NOT EXISTS billing_subscriptions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, provider text NOT NULL CHECK(provider IN ('stripe','apple','google')), provider_subscription_id text NOT NULL, livemode boolean NOT NULL, price_id text, plan text NOT NULL DEFAULT 'free', status text NOT NULL, current_period_end timestamptz, cancel_at_period_end boolean NOT NULL DEFAULT false, latest_invoice_id text, revoked_invoice_id text, updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS billing_subscription_provider_id ON billing_subscriptions(provider,provider_subscription_id,livemode);
CREATE INDEX IF NOT EXISTS billing_subscriptions_owner ON billing_subscriptions(user_id,livemode);
CREATE TABLE IF NOT EXISTS billing_events (id text PRIMARY KEY, type text NOT NULL, livemode boolean NOT NULL, processed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS auth_session (id text PRIMARY KEY, expires_at timestamp NOT NULL, token text NOT NULL UNIQUE, created_at timestamp NOT NULL, updated_at timestamp NOT NULL, ip_address text, user_agent text, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS auth_session_owner ON auth_session(user_id);
CREATE TABLE IF NOT EXISTS auth_account (id text PRIMARY KEY, account_id text NOT NULL, provider_id text NOT NULL, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, access_token text, refresh_token text, id_token text, access_token_expires_at timestamp, refresh_token_expires_at timestamp, scope text, password text, created_at timestamp NOT NULL, updated_at timestamp NOT NULL);
CREATE INDEX IF NOT EXISTS auth_account_owner ON auth_account(user_id);
CREATE TABLE IF NOT EXISTS auth_verification (id text PRIMARY KEY, identifier text NOT NULL, value text NOT NULL, expires_at timestamp NOT NULL, created_at timestamp, updated_at timestamp);
CREATE TABLE IF NOT EXISTS notebooks (id text PRIMARY KEY, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, name text NOT NULL, color text NOT NULL DEFAULT '#687354', created_at timestamp NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS notebooks_owner ON notebooks(user_id);
CREATE TABLE IF NOT EXISTS pages (id text PRIMARY KEY, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, notebook_id text NOT NULL REFERENCES notebooks(id) ON DELETE CASCADE, title text NOT NULL, document jsonb NOT NULL, version integer NOT NULL DEFAULT 1 CHECK(version > 0), updated_at timestamp NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS pages_owner_notebook ON pages(user_id, notebook_id);
CREATE TABLE IF NOT EXISTS page_revisions (page_id text NOT NULL REFERENCES pages(id) ON DELETE CASCADE, version integer NOT NULL, title text NOT NULL, document jsonb NOT NULL, mutation_id text NOT NULL, created_at timestamp NOT NULL DEFAULT now(), PRIMARY KEY(page_id, version), UNIQUE(page_id, mutation_id));
CREATE TABLE IF NOT EXISTS capture_sessions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, page_id text NOT NULL REFERENCES pages(id) ON DELETE CASCADE, call_id text, state text NOT NULL DEFAULT 'starting', stop_reason text, created_at timestamptz NOT NULL DEFAULT now(), active_at timestamptz, ended_at timestamptz, lease_expires_at timestamptz NOT NULL, deadline_at timestamptz NOT NULL, last_billed_at timestamptz, billed_ms integer NOT NULL DEFAULT 0, observer_id text);
CREATE INDEX IF NOT EXISTS capture_sessions_owner ON capture_sessions(user_id,state);
CREATE INDEX IF NOT EXISTS capture_sessions_expiry ON capture_sessions(state,lease_expires_at);
CREATE TABLE IF NOT EXISTS capture_usage (user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, period_start timestamptz NOT NULL, period_end timestamptz NOT NULL, used_ms bigint NOT NULL DEFAULT 0, PRIMARY KEY(user_id,period_start));
CREATE TABLE IF NOT EXISTS meeting_transcripts (id text PRIMARY KEY, session_id text NOT NULL REFERENCES capture_sessions(id) ON DELETE CASCADE, page_id text NOT NULL REFERENCES pages(id) ON DELETE CASCADE, item_id text NOT NULL, previous_item_id text, text text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS transcript_provider_item ON meeting_transcripts(session_id,item_id);
CREATE INDEX IF NOT EXISTS transcript_page ON meeting_transcripts(page_id);
CREATE TABLE IF NOT EXISTS capture_watchdog (id text PRIMARY KEY, checked_at timestamptz NOT NULL);
