BEGIN;
SET LOCAL search_path = sideleaf;
CREATE TABLE IF NOT EXISTS billing_customers (user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, livemode boolean NOT NULL, customer_id text, checkout_attempt text NOT NULL, checkout_session_id text, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id, livemode));
CREATE UNIQUE INDEX IF NOT EXISTS billing_customer_stripe_id ON billing_customers(customer_id);
CREATE TABLE IF NOT EXISTS billing_subscriptions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, provider text NOT NULL CHECK(provider IN ('stripe','apple','google')), provider_subscription_id text NOT NULL, livemode boolean NOT NULL, price_id text, plan text NOT NULL DEFAULT 'free', status text NOT NULL, current_period_end timestamptz, cancel_at_period_end boolean NOT NULL DEFAULT false, latest_invoice_id text, revoked_invoice_id text, updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS billing_subscription_provider_id ON billing_subscriptions(provider,provider_subscription_id,livemode);
CREATE INDEX IF NOT EXISTS billing_subscriptions_owner ON billing_subscriptions(user_id,livemode);
CREATE TABLE IF NOT EXISTS billing_events (id text PRIMARY KEY, type text NOT NULL, livemode boolean NOT NULL, processed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS capture_sessions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, page_id text NOT NULL REFERENCES pages(id) ON DELETE CASCADE, call_id text, state text NOT NULL DEFAULT 'starting', stop_reason text, created_at timestamptz NOT NULL DEFAULT now(), active_at timestamptz, ended_at timestamptz, lease_expires_at timestamptz NOT NULL, deadline_at timestamptz NOT NULL, last_billed_at timestamptz, billed_ms integer NOT NULL DEFAULT 0, observer_id text);
CREATE INDEX IF NOT EXISTS capture_sessions_owner ON capture_sessions(user_id,state);
CREATE INDEX IF NOT EXISTS capture_sessions_expiry ON capture_sessions(state,lease_expires_at);
CREATE TABLE IF NOT EXISTS capture_usage (user_id text NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, period_start timestamptz NOT NULL, period_end timestamptz NOT NULL, used_ms bigint NOT NULL DEFAULT 0, PRIMARY KEY(user_id,period_start));
CREATE TABLE IF NOT EXISTS meeting_transcripts (id text PRIMARY KEY, session_id text NOT NULL REFERENCES capture_sessions(id) ON DELETE CASCADE, page_id text NOT NULL REFERENCES pages(id) ON DELETE CASCADE, item_id text NOT NULL, previous_item_id text, text text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS transcript_provider_item ON meeting_transcripts(session_id,item_id);
CREATE INDEX IF NOT EXISTS transcript_page ON meeting_transcripts(page_id);
CREATE TABLE IF NOT EXISTS capture_watchdog (id text PRIMARY KEY, checked_at timestamptz NOT NULL);
ALTER TABLE sideleaf.billing_customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.billing_customers FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.billing_customers FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.billing_customers TO sideleaf_runtime;
ALTER TABLE sideleaf.billing_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.billing_subscriptions FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.billing_subscriptions FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.billing_subscriptions TO sideleaf_runtime;
ALTER TABLE sideleaf.billing_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.billing_events FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.billing_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.billing_events TO sideleaf_runtime;
ALTER TABLE sideleaf.capture_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.capture_sessions FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.capture_sessions FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.capture_sessions TO sideleaf_runtime;
ALTER TABLE sideleaf.capture_usage ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.capture_usage FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.capture_usage FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.capture_usage TO sideleaf_runtime;
ALTER TABLE sideleaf.meeting_transcripts ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.meeting_transcripts FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.meeting_transcripts FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.meeting_transcripts TO sideleaf_runtime;
ALTER TABLE sideleaf.capture_watchdog ENABLE ROW LEVEL SECURITY;
CREATE POLICY sideleaf_backend ON sideleaf.capture_watchdog FOR ALL TO sideleaf_runtime USING (true) WITH CHECK (true);
REVOKE ALL ON sideleaf.capture_watchdog FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sideleaf.capture_watchdog TO sideleaf_runtime;
COMMIT;
